version: "3.0"

services:
  api:
    build:
      context: .
    image: venue-services
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 4000
    links:
      - nats
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=4000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  accounts:
    build:
      context: .
    image: venue-services
    env_file: docker-compose.env
    environment:
      SERVICES: accounts
    links:
      - nats
    depends_on:
      - nats

  users:
    build:
      context: .
    image: venue-services
    env_file: docker-compose.env
    environment:
      SERVICES: users
    links:
      - nats
    depends_on:
      - nats

  constant-contact:
    build:
      context: .
    image: venue-services
    env_file: docker-compose.env
    environment:
      SERVICES: constant-contact
    links:
      - nats
    depends_on:
      - nats

  nats:
    image: nats

  redis:
    image: redis:alpine

  mongo:
    image: mongo
    volumes:
      - ./db:/data/db

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
