# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_and_test:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mongo:3.6.8-stretch
      - image: circleci/redis:4.0.11-alpine
      - image: nats:1.3.0

    working_directory: ~/venue-services

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: # run tests
          name: test
          command: npm test

  build_image:
    docker:
      - image: docker:18.06.1-ce
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: "Tag image and push to server"
          command: |
            TAG=v0.1.$CIRCLE_BUILD_NUM
            docker build -t volentixlabs/venue-services:$TAG .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker tag volentixlabs/venue-services:$TAG volentixlabs/venue-services:latest
            docker push volentixlabs/venue-services
            echo $TAG
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - build_image:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
